name: Prettier check

on:
  pull_request:
    paths:
      - apps/expo-app/**

jobs:
  prettier-check:
    name: Prettier check
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4

      - name: 🌿 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: "apps/expo-app/.nvmrc"
          cache: "yarn"

      - name: 📦 Install dependencies
        run: yarn install --immutable

      - name: ✨ Run Prettier check
        run: yarn run prettier:check
        working-directory: apps/expo-app
